spring:
  # default profile settings
  profiles:
    active: local

  # Spring Cloud 호환성 검사기 비활성화
  cloud:
    compatibility-verifier:
      enabled: false

  # 용량 제한 늘리기
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  sql:
    init:
      mode: never

# 로그인 jwt
jwt:
  secret: ${JWT_SECRET}
  accessExpirationTime: ${JWT_EXPIRATION}
  refreshExpirationTime: ${JWT_REFRESH_EXPIRATION}

# Open Ai
openai:
  secret-key: ${OPENAI_SECRET_KEY}
  url:
    prompt: https://api.openai.com/v1/completions

# s3
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
      path:
        location: location
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}

# swagger
springdoc:
  swagger-ui:
    path: /swagger
  cache:
    disabled: true
  use-fqn: true

# KOPIS API
kopis:
  key: ${KOPIS_KEY}
  api-url: http://www.kopis.or.kr/openApi/restful

logging:
  level:
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: TRACE

---

# local profile
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${local.db.url}
    username: ${local.db.username}
    password: ${local.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimum-idle: 20 # 최소 유지할 연결의 수
      maximum-pool-size: 50 # 최대 풀 크기
      idle-timeout: 600 # 10분. 사용되지 않는 연결이 유지될 최대 시간
      validation-timeout: 5000 # 5초. 연결 유효성 검사를 위한 타임아웃
      connection-timeout: 30000 # 30초. 연결을 시도할 때 최대 기다릴 시간
      max-lifetime: 5400 # 1시간 30분. 연결의 최대 수명

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #        format_sql: true
        #        show_sql: true
        #        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

---

# develop profile
spring:
  config:
    activate:
      on-profile: develop

  datasource:
    url: ${aws.db.url}
    username: ${aws.db.username}
    password: ${aws.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimum-idle: 20 # 최소 유지할 연결의 수
      maximum-pool-size: 50 # 최대 풀 크기
      idle-timeout: 600 # 10분. 사용되지 않는 연결이 유지될 최대 시간
      validation-timeout: 5000 # 5초. 연결 유효성 검사를 위한 타임아웃
      connection-timeout: 30000 # 30초. 연결을 시도할 때 최대 기다릴 시간
      max-lifetime: 5400 # 1시간 30분. 연결의 최대 수명

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #        format_sql: true
        #        show_sql: true
        #        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000