spring:
  # default profile settings
  profiles:
    active: local

  # Spring Cloud 호환성 검사기 비활성화
  spring:
    cloud:
      compatibility-verifier: enabled=false

  # 용량 제한 늘리기
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

# 로그인 jwt
jwt:
  secret: ${JWT_SECRET}
  accessExpirationTime: ${JWT_EXPIRATION}
  refreshExpirationTime: ${JWT_REFRESH_EXPIRATION}

# s3
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
      path:
        location: location
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}

# swagger
springdoc:
  swagger-ui:
    path: /swagger
  cache:
    disabled: true
  use-fqn: true

# KOPIS API
kopis:
  key: ${KOPIS_KEY}
  api-url: http://www.kopis.or.kr/openApi/restful

---

# local profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${local.db.url}
    username: ${local.db.username}
    password: ${local.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #        format_sql: true
        #        show_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
---

# develop profile
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: ${aws.db.url}
    username: ${aws.db.username}
    password: ${aws.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #        format_sql: true
        #        show_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000

# application.yml
logging:
  level:
    org:
      springframework:
        boot: DEBUG
